# Generated by Django 3.1.7 on 2021-03-19 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210319_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='files/')),
                ('url', models.URLField(blank=True)),
                ('desc', models.TextField(blank=True)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='banner_url',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.FileField(blank=True, upload_to='banners/'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
        migrations.AddField(
            model_name='postfile',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
